### ISSUE TITLE
Add more languages

### ISSUE THREAD

**Issue by pqvst** [pqvst/paperworks-talk#17]
Currently mainly English (and some Swedish) keywords are checked, like:
receipt, payment, invoice
faktura, kvitto
order

Feel free to suggest other languages (either here or by email):
hello@paperworks.io

**Comment by lchriqui** [comment]
Hi,

keywords in French : reçu, paiement, commande, facture

Thank you!!

**Comment by nelbu** [comment]
Hi! I find your app really helpful, so I want to collaborate to make it work in Spanish, so the main keywords are:
recibo, pago, factura, pedido

Thanks!

**Comment by pqvst** [comment]
Fixed. Pending release.
