### ISSUE TITLE
More than 1 year history

### ISSUE THREAD

**Issue by pqvst** [pqvst/paperworks-talk#43]

**Comment by berrehili** [comment]
It would be great to be able to have access to invoices of a specific month. It may not be synchronous but it would be great to have this quickly!

**Comment by pqvst** [comment]
Fixed, pending release. @berrehili I've added a temporary solution for fetching more history. I'll let you know when it's released.

**Comment by berrehili** [comment]
This is great! Will subscribe when it's released ;)
